// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendSense.Common.Data;

#nullable disable

namespace SpendSense.Migrations
{
    [DbContext(typeof(SpendSenseDbContext))]
    [Migration("20260420194800_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SpendSense.Common.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBudgetId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("SpendSense.Common.Models.ExpenseTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseTransactions");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IncomeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBudgetId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("SpendSense.Common.Models.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Savings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBudgetId");

                    b.ToTable("Savings");
                });

            modelBuilder.Entity("SpendSense.Common.Models.SavingsTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SavingsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SavingsId");

                    b.ToTable("SavingsTransactions");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Expense", b =>
                {
                    b.HasOne("SpendSense.Common.Models.MonthlyBudget", "MonthlyBudget")
                        .WithMany("Expenses")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyBudget");
                });

            modelBuilder.Entity("SpendSense.Common.Models.ExpenseTransaction", b =>
                {
                    b.HasOne("SpendSense.Common.Models.Expense", "Expense")
                        .WithMany("Transactions")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Income", b =>
                {
                    b.HasOne("SpendSense.Common.Models.MonthlyBudget", "MonthlyBudget")
                        .WithMany("Incomes")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyBudget");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Savings", b =>
                {
                    b.HasOne("SpendSense.Common.Models.MonthlyBudget", "MonthlyBudget")
                        .WithMany("Savings")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyBudget");
                });

            modelBuilder.Entity("SpendSense.Common.Models.SavingsTransaction", b =>
                {
                    b.HasOne("SpendSense.Common.Models.Savings", "Savings")
                        .WithMany("Transactions")
                        .HasForeignKey("SavingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Savings");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Expense", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SpendSense.Common.Models.MonthlyBudget", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Savings");
                });

            modelBuilder.Entity("SpendSense.Common.Models.Savings", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
